name: configmap-action
branding:
  icon: "settings"
  color: "white"
description: "Exports a ConfigMap as an job-outputs according to a given key, and consume it in other jobs with 'needs'"
inputs:
  configmap_key:
    required: false
    description: ""
    default: ""
  configmap_map:
    required: true
    description: ""
    default: "null"
outputs:
  CONFIGMAP_MAP:
    description: "The select configurations JSON, ready for re-use with fromJSON()"
    value: ${{ steps.export-configmap.outputs.CONFIGMAP_MAP }}
  CONFIGMAP_SELECTED_KEY:
    description: "The exported CONFIGMAP_MAP is based on this key"
    value: ${{ steps.export-configmap.outputs.CONFIGMAP_SELECTED_KEY }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: Export Configmap
      env:
        CONFIGMAP_KEY: ${{ inputs.configmap_key }}
        CONFIGMAP_MAP: ${{ inputs.configmap_map }}
        BARGS_PATH: ${{ github.action_path }}/bargs.sh
      id: export-configmap
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
    - name: Test Export
      # Fails if CONFIGMAP cannot be converted with fromJSON
      # Better finding it out here and avoid triggering the next jobs
      run: |
        echo ${{ steps.export-configmap.outputs.CONFIGMAP_SELECTED_KEY }}
        echo ${{ fromJSON(steps.export-configmap.outputs.CONFIGMAP_MAP) }}
      shell: bash
